### ISSUE TITLE
Single `'` quotes don't work

### ISSUE THREAD

**Issue by benthillerkus** [facebook/sapling#230]
In the docs, various commands use `'` quotes to enclose strings:

```
$ sl config --user ui.username 'Alyssa P. Hacker <alyssa@example.com>'
...
$ sl commit -m 'my first commit with Sapling'
```

however, on my machine (Windows, `cmd`, German locale), these commands only work when using `"` double quotes.

**Comment by shish** [comment]
Looks like this is just how `cmd` works, and is considered normal behaviour for that shell - so the fix would be to update the docs to use double quotes since those work everywhere (whereas single quotes work everywhere-except-`cmd`)

(It seems that on windows, args are passed to the process as a single string rather than an array, so it _could_ be possible for an application to add its own support for single-quote strings, but that would be non-standard? My gut tells me that updating the docs rather than the code is better in this case)

**Comment by bolinfest** [comment]
I was touching this line as part of https://github.com/facebook/sapling/commit/596bc1c36393e9c2d49b222e154f4982508eab6f anyway, so I switched to double quotes in that commit.

GitHub's documentation for setting a username in Git also uses double quotes, possibly for this reason?

https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git
