### ISSUE TITLE
`sl pr list` exits before returning data

### ISSUE THREAD

**Issue by francois** [facebook/sapling#363]
Running `sl pr list` returns to the command line, then a few moments later (< 1 second), the PR list is printed:

```
╰─○ sl pr list
╰─○
Showing 2 of 2 open pull requests in Inspectify/marketplace

#732  Some title  pr732                         about 3 days ago
#622  Some title  feature/remove_success_again  about 28 days ago
```

```
╰─○ sl --version
Sapling 0.2.20221222-152408
╰─○ brew --version
Homebrew 3.6.16
Homebrew/homebrew-core (git revision 4c7d9dfaa44; last commit 2022-12-27)
Homebrew/homebrew-cask (git revision 82cb73dc4c; last commit 2022-12-27)
╰─○ gh --version
gh version 2.21.1 (2022-12-23)
https://github.com/cli/cli/releases/tag/v2.21.1
```

**Comment by muirdm** [comment]
Thanks for the report. It looks related to the pre-fork server used to speed up commands, combined with the exec of the "gh" command to list prs. An upcoming change should resolve this.

**Comment by bolinfest** [comment]
@quark-zju I am having a lot of trouble finding the code that maps requests from the client to the server for `ui.system()`. I see this comment:

https://github.com/facebook/sapling/blob/d0936284bd7208707ccf57a83a8faf7b26e587e5/eden/scm/edenscm/chgserver.py#L15-L16

and this code:

https://github.com/facebook/sapling/blob/d0936284bd7208707ccf57a83a8faf7b26e587e5/eden/scm/edenscm/chgserver.py#L130

But I don't see where the server maps `b"s"` to `system()` or `_runsystem()` or whatever it is supposed to be.

Trying to escape arguments and concatenate them with spaces to create an equivalent `cmd` as a single string is quite a pain because `shlex()` is not designed to support Windows. I want to add an RPC that takes the args as an array and invokes `subprocess.call()` with `shell=False`.

**Comment by quark-zju** [comment]
> But I don't see where the server maps `b"s"` to `system()` or `_runsystem()` or whatever it is supposed to be.

Is https://github.com/facebook/sapling/blob/d0936284bd7208707ccf57a83a8faf7b26e587e5/eden/scm/contrib/chg/hgclient.c#L230 what you look for?
 
> Trying to escape arguments and concatenate them with spaces to create an equivalent `cmd` as a single string is quite a pain because `shlex()` is not designed to support Windows. I want to add an RPC that takes the args as an array and invokes `subprocess.call()` with `shell=False`.

There is `util.shellquote` for cross-platform escaping.

**Comment by bolinfest** [comment]
@quark-zju thanks, I had my search restricted to the Python code. chg seems like a candidate for a Rust rewrite?

Regardless, I'll try `util.shellquote()` to address the issue in the short-term. Long-term, I would still prefer to get away from passing the command as an opaque string.

**Comment by bolinfest** [comment]
I developed https://github.com/facebook/sapling/pull/377 on Windows, but will test on macOS with chg running.
