### ISSUE TITLE
How does one self-review and merge their own PRs?

### ISSUE THREAD

**Issue by martpie** [facebook/sapling#699]
GitHub // ReviewStack // `sl pr`  // [Example PR](https://github.com/martpie/museeks/pull/723)

This might be out of ReviewStack responsibility. 

I am the only developer of an open-source project. I still use PR as a way to self-review my code, and use Sapling and ISL to organize my commits atomically. 

How do I get my diffs stack merged? 

- If I merge by the first diff, it creates conflicts on subsequent diffs
- If I merge by the top diff, I have to manually close all previous diffs (is that intended?)
- Unless I'm wrong, ReviewStack is only about reviewing, not merging

Maybe I am missing something, but is there some official guidance for this pattern?

**Comment by evangrayk** [comment]
There's certainly a few rough edges here still.

If you have write access to a repo, then `sl ghstack` is probably closer to what you want. It has some advantages over `sl pr`:
- stacked PRs are not overlapping, so you can read them in GitHub/Review stack normally
- Landing a stack works better, but you have to use `sl ghstack land` instead of going to github to merge it

[See documentation for sl ghstack](https://sapling-scm.com/docs/commands/ghstack/)

`sl pr` on the other hand doesn't require write access to the repo and supports landing/merging through GitHub. But it requires landing the top of the stack, as you noticed, and PRs contain overlapping code. 

These limitations are unfortunately due to how GitHub works right now, so we don't have much wiggle room to improve this experience.

I'm not sure if this is our official guidance, but I've had success by using `sl ghstack` when I have write access to a repo, and merging with `sl ghstack land`. You can use ReviewStack or GitHub to do code reviews.

Hope this helps a little.

**Comment by martpie** [comment]
I think we can close this :)

**Comment by AhmedSoliman** [comment]
When merging the top of the stack, which github merge mode is supported by sapling "squash, rebase, or merge commit"? I ask because after merging the top with a rebase, `sl pull` can see that the top of "landed" but parent commits are not. Any advise on what's the strategy should be here?
