### ISSUE TITLE
Mononoke binaries aren't actually published

### ISSUE THREAD

**Issue by thoughtpolice** [facebook/sapling#922]
Hi,

I saw the announcement in the README about the Mononoke backend working. That's exciting! I'm happy to dig into it myself and play around, but...

It looks like the binary builds aren't working &mdash; for Mononoke, specifically. They *do* work for EdenFS. Note that none of the runs here have artifacts published and there's even a warning from the `upload-artifact` action that no paths were found to upload: https://github.com/facebook/sapling/actions/workflows/mononoke_linux.yml

Also: is a new Sapling client required to interface with Mononoke? I assume so, but I know nothing. Should there be a new release done in order to allow testing the two?

**Comment by Matthew-Benson** [comment]
I was able to follow the same steps for Mononoke's build process that's running in CI and got a `mononoke` binary, but I'm fairly sure the artifact path in [this job step](https://github.com/facebook/sapling/blob/41c4ca7e7e2b86385ec8224e286f4268fbf3b15d/.github/workflows/mononoke_linux.yml#L171-L174) is wrong and that's why nothing gets uploaded. I'm not sure if that's intentional or not.

It has been a while, but I have in my notes that the path for the mononoke binary was `/tmp/fbcode_builder_getdeps-ZhomeZrunnerZsaplingZbuildZfbcode_builder/installed/mononoke/bin/mononoke`.

There's some detail about it in https://github.com/facebook/sapling/issues/812.

**Comment by mzr** [comment]
The builds of Mononoke aren't as well supported as builds of Sapling at this time. I don't recall we tried full setup of EdenFS, Monoonke and Sapling together outside of the internal use at Meta, but I might be wrong on this one.
As for tinkering at the moment, perhaps @ahornby who has done some work around this might be better positioned to give some advice.

> Also: is a new Sapling client required to interface with Mononoke? 

The best supported use-case right now is Sapling as client for git repositories. You can read more about this in https://sapling-scm.com/.

**Comment by thoughtpolice** [comment]
Oh, I've used `sl` quite a bit for Git! But it was more that this commit that flew by recently in the [Jujutsu](https://github.com/martinvonz/jj) Discord is what had me interested (as we are interested in our own non-Git backend): https://github.com/facebook/sapling/commit/e2f00faac305433c82075c88d20719e0dd4dac62

I knew that the binaries weren't previously supported, but it at least seemed like there were supposed to be (undocumented) binaries published. Hence the original issue. :)

**Comment by ahornby** [comment]
Sapling thrift client build added in https://github.com/facebook/sapling/pull/950

**Comment by ahornby** [comment]
Mononoke integration tests using it in https://github.com/facebook/sapling/pull/951
